language: python
python: 3.7

servies: docker

jobs:
  include:
    - arch: amd64
      install: docker build -t b2-base -f Dockerfile .
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      install: docker build -t b2-base -f Dockerfile.arm .


script: 
  - scripts/run_dev_tests.sh nomount coveralls

deploy:
  - provider: script
    script: scripts/travis_deploy_dockerhub.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "dev"
